### ISSUE TITLE
pycrypto is gone

### ISSUE THREAD

**Issue by bokskog** [pycontribs/django-alexa#35]
Hey
I'm trying to build a skill with django-alexa for the first time.
Seems like pycrypto is dead. It can't be downloaded, and it's developers have said that dependencies should be changed to PyCryptodome:
dlitz/pycrypto#238

But django-alexa depends on pycrypto. PyCharm tells me:
django-alexa 0.0.7 requires pycrypto>=2.6.1, which is not installed.
But pip install pycrypto==2.6.1     -->failed with error code 1 in C:\ ...

Can I just not use django-alexa until this is fixed? I'm intermediate-beginner with python and django.

@rocktavious

**Comment by hairychris** [comment]
In your position I'd fork this library, make the one line change to update from PyCrypto to PyCryptodrome and then put in a pull request. Whilst you are waiting for this to be accepted you can install your version directly from git like so:

````
pip install git+git://github.com/bokskog/django-alexa.git#egg=django-alexa
````

**Comment by bokskog** [comment]
Thanks for your comment!
I did change the requirements file and made a pull request.
However the pip install command is still looking for pycrypto, and I still get the same error.. Even after restarting the terminal. I don't know if I misunderstood or did something wrong. 

And a bit of a side question - but can you just update the requirements like that? Isn't pycrypto there because django-alexa actually depends on some of its methods, and now it'll all break?

**Comment by hairychris** [comment]
I can't see any pull requests for this library, are you sure you have done it? Check here and it should show up: https://github.com/pycontribs/django-alexa/pulls

The line you want to change is: https://github.com/pycontribs/django-alexa/blob/master/requirements.txt#L1 which should read:

````
pycryptodome==3.6.1
````

As for why this is ok to do it's because PyCryptoDome is API compatible with PyCrypto so all of the methods (etc) that we require will be there.

All of that said I've not used this library in a long time and it doesn't look maintained so even if you do get it working something might have changed at Amazon's end that breaks stuff. You might be better off exploring alternatives.

**Comment by lingster** [comment]
@bokskog I've just submitted a PR and merged changes so that this project now uses pycryptodome. In additional support for python 2.7 has been removed so that going forward this project can use Django 2.x(for which legacy python 2 support is no more). Please let me know if you have any further issues.

**Comment by lingster** [comment]
Closing this ticket as no response
